### ISSUE TITLE
Endpoints throws InvalidOperationException on startup when there is already another running endpoint (run as different user) with performance counters

### ISSUE THREAD

**Issue by sanilpaul** [Particular/NServiceBus.Metrics.PerformanceCounters#176] opened 2021-03-15 16:31 UTC
Endpoints throws InvalidOperationException on startup when there is already another endpoint (run as different user) with performance counters enabled and on `netcoreapp3.1` 

Here are the steps to reproduce. 
Starting point: sample provided here. https://docs.particular.net/samples/sqltransport/simple/
Add this code to enable performance counters on both sender and Receiver. 

```c#
var performanceCounters = endpointConfiguration.EnableWindowsPerformanceCounters();
performanceCounters.EnableSLAPerformanceCounters(TimeSpan.FromSeconds(100));
```

Run one of the endpoint as different user. The user is added to Performance Log users and Performance monitor users. 
Which ever endpoint that starts second throws the exception

```txt
System.Exception
  HResult=0x80131500
  Message=NServiceBus performance counter for 'SLA violation countdown' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation.
  Source=NServiceBus.Metrics.PerformanceCounters
  StackTrace:
   at PerformanceCountersCache.CreateInstance(CounterInstanceName counterInstanceName)

  This exception was originally thrown at this call stack:
    System.Diagnostics.SharedPerformanceCounter.FileMapping.Initialize(string, int, int) in SharedPerformanceCounter.cs
    System.Diagnostics.SharedPerformanceCounter.GetCategoryData() in SharedPerformanceCounter.cs
    System.Diagnostics.SharedPerformanceCounter.SharedPerformanceCounter(string, string, string, System.Diagnostics.PerformanceCounterInstanceLifetime) in SharedPerformanceCounter.cs
    System.Diagnostics.PerformanceCounter.InitializeImpl() in PerformanceCounter.cs
    System.Diagnostics.PerformanceCounter.Initialize() in PerformanceCounter.cs
    System.Diagnostics.PerformanceCounter.PerformanceCounter(string, string, string, bool) in PerformanceCounter.cs
    PerformanceCountersCache.CreateInstance(CounterInstanceName)

Inner Exception 1:
InvalidOperationException: Cannot create file mapping.
```

More details on the setup

```txt
NServiceBus - 7.4.4
NServiceBus.Metrics.PerformanceCounters - 4.0.0
NServiceBus.Transport.SqlServer - 6.2.0
Runtime : netcoreapp3.1 

* Counters on the machine
\NServiceBus(*)\SLA violation countdown
\NServiceBus(*)\Critical Time Average
\NServiceBus(*)\Critical Time
\NServiceBus(*)\Processing Time Average
\NServiceBus(*)\Processing Time
\NServiceBus(*)\# of msgs failures / sec
\NServiceBus(*)\# of msgs successfully processed / sec
\NServiceBus(*)\# of msgs pulled from the input queue /sec
\NServiceBus(*)\Retries

```

Any help to get past the issue would be appreciated.

**Comment by ramonsmits** [comment] 2021-03-16 18:16
@sanilpaul If you are dealing with a version migration and the previous version was a very old version it might be that the performance counters need to be recreated as in the past additional metrics have been added.

The following describes how to recreate the NServiceBus Windows Performance Counters Category:

<https://docs.particular.net/monitoring/metrics/performance-counters#installing-counters-force-category-recreation>

This revised category is backward compatible with all previous NServiceBus versions.

However, recreating the category most likely requires all dependencies on that category to not be running. If you experience errors ensure that all NServiceBus endpoints on that machine are stopped and that no metrics services are currently trying to capture any metrics on this category.

**Comment by sanilpaul** [comment] 2021-03-16 18:23
@ramonsmits I did all the steps you are mentioning. Are you not able to reproduce the issue?

**Comment by ramonsmits** [comment] 2021-03-16 18:49
@sanilpaul I did not try to reproduce yet as I wanted to ensure the category was created correctly. Can you also reproduce this with the <https://docs.particular.net/samples/performance-counters/> sample?

**Comment by sanilpaul** [comment] 2021-03-16 18:56
@ramonsmits Ok. understood. 
The performance-counters sample has only 1 endpoint. This happens when you have more than 1 endpoint. And the second endpoint should run as different user. Like I said in the description, I reproduced the issue with sql server sample.

**Comment by ramonsmits** [comment] 2021-03-16 18:58
@sanilpaul were either of the accounts running with elevated permissions or regular users?

**Comment by sanilpaul** [comment] 2021-03-16 19:11
regular users. Both are part of Performance log users and Performance monitor users groups.

**Comment by ramonsmits** [comment] 2021-03-16 19:29
1. Created to users `test` and `test2`.
2. Ran `net localgroup "Performance Monitor Users" "ZOLDER\test" /add`
3. Ran `net localgroup "Performance Monitor Users" "ZOLDER\test2" /add`
4. Modified the performance counter sample: <https://github.com/ramonsmits/docs.particular.net/tree/perfcounters-multiple-users/samples/performance-counters/PerfCounters_4>
5. Opened 2 consoles via `runas /user:test2 cmd` and `runas /user:test cmd`
6. Ran the `net48` and `netcoreapp3.1` builds without issues.

![chrome_2021-03-16_20-28-05](https://user-images.githubusercontent.com/152998/111368467-378aed00-8696-11eb-91c7-7993ba07d0d3.png)

**Comment by ramonsmits** [comment] 2021-03-16 19:38
@sanilpaul The exception `InvalidOperationException: Cannot create file mapping.` seems to be related to the state where the OS is in.

The fact that you get the message "NServiceBus performance counter for 'SLA violation countdown' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation." indicates something is not setup correctly with the performance counters. Maybe there is Windows Performance Counter corruption as mentioned in our guidance <https://docs.particular.net/monitoring/metrics/performance-counters#corrupted-counters>

Hopefully running `lodctr /r` on an elevated prompt helps to resolve your issue.

**Comment by sanilpaul** [comment] 2021-03-16 19:39
@ramonsmits Can you follow the exact steps I mentioned in the steps to reproduce? https://docs.particular.net/samples/sqltransport/simple/ 

And let me know what's wrong in the code and how our production code should look like.

**Comment by sanilpaul** [comment] 2021-03-16 19:49
> @sanilpaul The exception `InvalidOperationException: Cannot create file mapping.` seems to be related to the state where the OS is in.
> 
> The fact that you get the message "NServiceBus performance counter for 'SLA violation countdown' is not set up correctly. To rectify this problem, consult the NServiceBus performance counters documentation." indicates something is not setup correctly with the performance counters. Maybe there is Windows Performance Counter corruption as mentioned in our guidance https://docs.particular.net/monitoring/metrics/performance-counters#corrupted-counters
> 
> Hopefully running `lodctr /r` on an elevated prompt helps to resolve your issue.

Did all those. This happened repeatedly in our regression testing environment with newly provisioned VMs And then I reproduced it locally with sample provided on your site to rule out any side effects caused by our code.

**Comment by ramonsmits** [comment] 2021-03-16 20:16
@sanilpaul Although my previous sample already ran 2 different endpoints with performance counters enabled I've applied on your request the same to the SQL Transport sample to be equal with your setup.

<https://github.com/ramonsmits/docs.particular.net/tree/perfcounters-multiple-users/samples/sqltransport/simple/SqlTransport_6>

1. Granted access for `test` and `test2` to the database.
2. Ran `launch.cmd` to run receiver and sender as 2 different normal users

This also runs without any issues.

![image](https://user-images.githubusercontent.com/152998/111372529-09f47280-869b-11eb-86ef-c6787633155e.png)

Environment version info:

```
Environment.Version: 4.0.30319.42000
Environment.OSVersion: Microsoft Windows NT 6.2.9200.0
RuntimeInformation.FrameworkDescription: .NET Framework 4.8.4341.0
```

Please review my branch to see if I'm missing any significant changes that might be different from your test.

What happens when you skip `endpointConfiguration.EnableInstallers();`?

**Comment by sanilpaul** [comment] 2021-03-17 11:07
@ramonsmits  I repeated my tests on net48 and it works. 
The issue is if your target framework is `netcoreapp3.1` . I disabled the installers in the sample. 
Can you repeat your tests with `netcoreapp3.1` as your target framework and let me know.

**Comment by ramonsmits** [comment] 2021-03-17 11:47
@sanilpaul As requested

```
Environment.Version: 3.1.13
Environment.OSVersion: Microsoft Windows NT 6.2.9200.0
RuntimeInformation.FrameworkDescription: .NET Core 3.1.13
```
See source at <https://github.com/ramonsmits/docs.particular.net/tree/perfcounters-multiple-users/samples/sqltransport/simple/SqlTransport_6>

![](https://user-images.githubusercontent.com/152998/111462070-45845080-871e-11eb-9f77-9222c5420b39.png)

**Comment by sanilpaul** [comment] 2021-03-17 12:17
hmm.. seems like there is something else in play here.  Sent you the full screen shot in email. 
I ran your exact same code and this is what I get on my local box as well as on a newly provisioned machine in a different environment. The only difference is I got 3.1.12 vs 3.1.13. I will repeat my tests after upgrading to 3.1.13. 
![image](https://user-images.githubusercontent.com/484817/111466023-21fadf00-86f9-11eb-90c7-d395b02faed5.png)

![image](https://user-images.githubusercontent.com/484817/111465469-85384180-86f8-11eb-8988-7a9e329154aa.png)

**Comment by sanilpaul** [comment] 2021-03-17 12:28
![image](https://user-images.githubusercontent.com/484817/111467383-c16ca180-86fa-11eb-9fbc-8afa2e9a96a3.png)

![image](https://user-images.githubusercontent.com/484817/111467332-b44fb280-86fa-11eb-8e40-a61ac9a2d564.png)

**Comment by ramonsmits** [comment] 2021-03-17 14:10
@sanilpaul As this is seems to be something related to your environment and maybe the counters. I've updated my modified sample to report the category and counter existence for *SLA violation countdown*. Could you please run this? I would expect both to report `True`.

**Comment by sanilpaul** [comment] 2021-03-17 14:24
It sounds like it. The behavior I observed so far is if I start sender first, receiver would throw exception and vice versa.  Going to test it on different machines as well as see whether there is any issue with `System.Diagnostics.PerformanceCounter` package itself. Thanks for your help. Let me know if you have any ideas.
Here is the result of those commands
![image](https://user-images.githubusercontent.com/484817/111482234-1663e400-870a-11eb-80a5-0bb1a6bcfa41.png)

**Comment by ramonsmits** [comment] 2021-03-17 17:14
@sanilpaul Are you only experiencing this with .net core or also with .net framework?

**Comment by sanilpaul** [comment] 2021-03-17 18:07
@ramonsmits  .net Framework works fine. We are seeing this only with .net core. 
Here is what I observed with my further tests. I verified 2 of our work machines and on my personnel one. 

1. Restart the machine. so none of the previous instances are in performance monitor
2. Run the netcoreapp3.1 version of sender and receiver( as two different users)
3. Which ever endpoint starts last throws the exception
4. Open up performance monitor and none of the endpoints are in the instances for NSB category
5. Run the net48 version of sender and receiver ( as two different users) 
6. Endpoint runs fine. Performance monitor reports counters for 2 instances. 
7. Add the instances as selected object
7. Run the netcoreapp3.1 version of sender and receiver( as two different users)
8. And it runs fine. 

We can have a call if it makes more sense to observe what am talking about if you are unable to reproduce on your machine.

**Comment by ramonsmits** [comment] 2021-03-17 21:37
@sanilpaul I've restarted my machine and then I can also reproduce it with `netcoreapp3.1`. Infact, it now keeps failing in this session and the same for my earlier sample.

Based on your observation it seems that .net core 3.1 doesn't allow to create multiple instances under different credentials

I've created the smallest reproduction indicating this is an issue with .net core:

```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main()
    {
        if (!PerformanceCounterCategory.Exists("Test"))
        {
            Console.WriteLine("Creating");
            PerformanceCounterCategory.Create("Test", "Multi user instance test", PerformanceCounterCategoryType.MultiInstance, "Test", "Test");
        }

        using var counter = new PerformanceCounter("NServiceBus", "Retries", Guid.NewGuid().ToString("n"), false);
        Console.ReadLine();
    }
}
```

I then updated the package `System.Diagnostics.PerformanceCounter` to 5.0.1 which resulted in the same exception. I then upgraded to the latest prerelease which is 6.0.0-preview.2 and that works. I then downgraded to 6.0.0-preview.1 and there the problem still exists. The problem got fixes between the last 2 prereleases. I've not yet found any evidence that specifically mentions this bug.

## Workaround to resolve the issue

The workaround is to force target the ternary dependency to the latest prerelease in your .csproj by adding:

```xml
<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="6-*" />
```

or just target the latest of any major:

```xml
<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="*-*" />
```

I've added these to the sample projects I tested and this works: https://github.com/ramonsmits/docs.particular.net/tree/perfcounters-multiple-users/samples/sqltransport/simple/SqlTransport_6

I'm not sure this fix would actually work for all projects or for a production deployment as more ternary dependencies are now targeting the other runtime assemblies part of preview 2.

**Comment by ramonsmits** [comment] 2021-03-17 22:09
@sanilpaul I've created the following bug issue https://github.com/dotnet/runtime/issues/49782 and partially used your reproduction steps. You might want to add additional details if they are related to the bug instead of NServiceBus.

**Comment by ramonsmits** [comment] 2021-03-19 08:03
@sanilpaul As this is a issue with .net core we can't do more than what we've done so far and will close this issue.

As you are migrating to .net core you might also prepare be preparing for not hosting in Windows. If that is the case then you will have to remove the dependency on Windows Performance Counters. Potentially an alternative to using the Windows Performance Counters would be using [Performance Metrics in ServicePulse](https://docs.particular.net/monitoring/metrics/in-servicepulse) or to capture metric data in a custom destination like [Datadog](https://docs.particular.net/samples/logging/datadog/), [NewRelic](https://docs.particular.net/samples/logging/new-relic/), [Prometheus](https://docs.particular.net/samples/logging/prometheus-grafana/) or [capture the raw data and send to any destination you want](https://docs.particular.net/monitoring/metrics/raw).

If you have any questions on that then please see <https://particular.net/support>

**Closed by ramonsmits** 2021-03-19 08:03 UTC
